name: "Publish Node"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'hal-wang/Lavcode'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup ENV
        env:
          SECRET_KEY: ${{ secrets.NODE_SECRET_KEY }}
          ENV_ID: ${{ secrets.NODE_ENV_ID }}
        run: |
          cd src/lavcode-node
          npm install
          echo -e "SECRET_KEY=$SECRET_KEY\nENV_ID=$ENV_ID" > ./.env.local
      - name: Publish
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: |
          cd src/lavcode-node
          npx tcb login --apiKeyId $TENCENT_SECRET_ID --apiKey $TENCENT_SECRET_KEY
          npx tcb framework deploy --mode local
