name: "Publish Docs"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'hal-wang/Lavcode'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        env:
          SECRET_KEY: ${{ secrets.NODE_SECRET_KEY }}
          ENV_ID: ${{ secrets.NODE_ENV_ID }}
        run: |
          npm i -g yarn --force
          yarn config set registry https://registry.npmjs.org
          cd docs
          yarn install
          yarn build

      - name: Init-Git
        run: |
          cd docs/.vuepress/dist
          git config --global user.name 'hal-wang' 
          git config --global user.email 'hi@hal.wang'
          git init -b gh-pages
          git add -A
          git commit -m "publish"

      - name: Publish
        uses: ad-m/github-push-action@master
        with:
          directory: docs/.vuepress/dist
          repository: hal-wang/Lavcode
          force: true
          branch: gh-pages
          github_token: ${{ secrets.PUSH_REPO }}
